name: Upload Release Assets

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  upload_release_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download OpenCV iOS Framework
        run: |
          wget https://github.com/opencv/opencv/releases/download/${{ github.event.inputs.version }}/opencv-${{ github.event.inputs.version }}-ios-framework.zip
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            opencv-${{ github.event.inputs.version }}-ios-framework.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: |
            OpenCV iOS Framework
          draft: true
          prerelease: true

      - name: Get assets URL
        id: get_assets_url
        run: |
          ASSETS_URL=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }} | jq -r '.assets[0].url')
          echo "ASSETS_URL=$ASSETS_URL" >> $GITHUB_ENV

      - name: Echo Release URL
        run: |
          echo "url - ${{ steps.create_release.outputs.url }}"
          echo "id - ${{ steps.create_release.outputs.id }}"
          echo "upload_url - ${{ steps.create_release.outputs.upload_url }}"
          echo "assets_url - ${{ env.ASSETS_URL }}"
