name: Upload Release Assets

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  upload_release_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download OpenCV iOS Framework
        run: |
          wget https://github.com/opencv/opencv/releases/download/${{ github.event.inputs.version }}/opencv-${{ github.event.inputs.version }}-ios-framework.zip
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            opencv-${{ github.event.inputs.version }}-ios-framework.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: |
            OpenCV iOS Framework
          draft: false
          prerelease: true

      - name: Echo Release URL
        run: |
          echo "url - ${{ steps.create_release.outputs.url }}"
          echo "id - ${{ steps.create_release.outputs.id }}"
          echo "upload_url - ${{ steps.create_release.outputs.upload_url }}"
          echo "assets_url - ${{ steps.create_release.outputs.assets }}"
